# QueryNode Infrastructure
version: '3.4'
services:
  joystream-node:
    image: joystream/node:76f7f9d6fb20e85308d9b055d9698a654759c930
    restart: unless-stopped
    container_name: joystream-node
    volumes:
      - ${CHAIN_BASE_PATH}:/chain
      - ./joy-mainnet.json:/joy-mainnet.json
    command: >
      --pruning=archive
      --ws-external --rpc-cors all
      --unsafe-ws-external --unsafe-rpc-external --rpc-methods Safe
      --base-path /chain
      --chain /joy-mainnet.json
    ports:
      - '127.0.0.1:9944:9944'
      - '127.0.0.1:9933:9933'

  db:
    image: postgres:14
    container_name: db
    restart: unless-stopped
    ports:
      - '127.0.0.1:${DB_PORT}:${DB_PORT}'
    volumes:
      - ${DATABASE_VOLUME}:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASS}
      PGPORT: ${DB_PORT}

  graphql-server:
    image: joystream/query-node:1.2.1
    container_name: graphql-server
    restart: unless-stopped
    environment:
      - DB_HOST=db
      - DB_PASS=${DB_PASS}
      - DB_USER=${DB_USER}
      - DB_PORT=${DB_PORT}
      - DB_NAME=${PROCESSOR_DB_NAME}
      - GRAPHQL_SERVER_PORT=${GRAPHQL_SERVER_PORT}
      - GRAPHQL_SERVER_HOST=localhost
      # - WARTHOG_APP_PORT=${GRAPHQL_SERVER_PORT}
      # - WARTHOG_APP_HOST=graphql-server
      # Query node playground endpoint
      # Leave it blank if you want endpoint to be copied from browser's URL
      - GRAPHQL_PLAYGROUND_ENDPOINT=
      # Query node playground subscription endpoint
      # will be derived from GRAPHQL_PLAYGROUND_ENDPOINT when not set
      # - GRAPHQL_PLAYGROUND_SUBSCRIPTION_ENDPOINT=
      # URL for CDN serving QN Playground's JS/CSS files - set empty string for local file serving
      - GRAPHQL_PLAYGROUND_CDN_URL=
      - TYPEORM_LOGGING=error
      - PROCESSOR_HOST=processor
      - PROCESSOR_STATE_APP_PORT=${PROCESSOR_STATE_APP_PORT}
    ports:
      - "${GRAPHQL_SERVER_PORT}:${GRAPHQL_SERVER_PORT}"
      - "127.0.0.1:${PROCESSOR_STATE_APP_PORT}:${PROCESSOR_STATE_APP_PORT}"
    depends_on:
      - db
      - processor
    working_dir: /joystream
    command: ['workspace', 'query-node-root', 'query-node:start:prod']

  processor:
    image: joystream/query-node:1.2.1
    container_name: processor
    restart: unless-stopped
    environment:
      - WARTHOG_DB_HOST=db
      - WARTHOG_DB_DATABASE=${PROCESSOR_DB_NAME}
      - WARTHOG_DB_USERNAME=${DB_USER}
      - WARTHOG_DB_PASSWORD=${DB_PASS}
      - WARTHOG_APP_PORT=4002
      - DB_HOST=db
      - DB_PASS=${DB_PASS}
      - DB_USER=${DB_USER}
      - DB_PORT=${DB_PORT}
      - DB_NAME=${PROCESSOR_DB_NAME}
      - INDEXER_ENDPOINT_URL=${PROCESSOR_INDEXER_GATEWAY}
      - TYPEORM_HOST=db
      - TYPEORM_DATABASE=${PROCESSOR_DB_NAME}
      - BATCH_SIZE=100
      - QUEUE_FACTOR=1
      - QUEUE_MAX_CAP_FACTOR=4
      - DEBUG=hydra-processor:event-queue
      - TYPEORM_LOGGING=error
      # State update endpoint used by prcessor (to send state updates)
      - STATE_UPDATE_ENDPOINT=http://graphql-server:${PROCESSOR_STATE_APP_PORT}/update-processor-state
    depends_on:
      - db
    working_dir: /joystream
    entrypoint: sh
    command: >
      -c "
        yarn workspace query-node-root db:prepare ;
        yarn workspace query-node-root db:migrate ;
        yarn workspace query-node-root processor:start
      "

  indexer:
    image: joystream/hydra-indexer:v5.0.0-alpha.1
    container_name: indexer
    restart: unless-stopped
    environment:
      - DB_NAME=${INDEXER_DB_NAME}
      - DB_PASS=${DB_PASS}
      - DB_USER=${DB_USER}
      - DB_PORT=${DB_PORT}
      - INDEXER_WORKERS=5
      - REDIS_URI=redis://redis:6379/0
      - WS_PROVIDER_ENDPOINT_URI=${JOYSTREAM_NODE_WS}
      - DB_HOST=db
      - DEBUG=hydra-indexer:substrate-service
      # Block height to start indexing from.
      # Note, that if there are already some indexed events, this setting is ignored
      - BLOCK_HEIGHT=0
      - TYPEORM_LOGGING=error
    depends_on:
      - db
      - redis
    command: >
      sh -c "yarn db:bootstrap && yarn start:prod"

  hydra-indexer-gateway:
    image: joystream/hydra-indexer-gateway:5.0.0-alpha.1
    container_name: hydra-indexer-gateway
    restart: unless-stopped
    environment:
      - WARTHOG_STARTER_DB_DATABASE=${INDEXER_DB_NAME}
      - WARTHOG_STARTER_DB_HOST=db
      - WARTHOG_STARTER_DB_PASSWORD=${DB_PASS}
      - WARTHOG_STARTER_DB_PORT=${DB_PORT}
      - WARTHOG_STARTER_DB_USERNAME=${DB_USER}
      - WARTHOG_STARTER_REDIS_URI=redis://redis:6379/0
      - WARTHOG_APP_PORT=${HYDRA_INDEXER_GATEWAY_PORT}
      - PORT=${HYDRA_INDEXER_GATEWAY_PORT}
      # - DEBUG=*
    ports:
      - "${HYDRA_INDEXER_GATEWAY_PORT}:${HYDRA_INDEXER_GATEWAY_PORT}"
    depends_on:
      - db
      - redis

  redis:
    image: redis:6.0-alpine
    container_name: redis
    restart: unless-stopped
    ports:
      - "127.0.0.1:6379:6379"
